### ISSUE TITLE
zanehitchcox.com gives 404 error

### ISSUE THREAD

**Issue by DennisLfromGA** [zwhitchcox/resume#1]
When I click on [zanehitchcox.com](http://zanehitchcox.com/), I get -

![screenshot 2016-10-15 at 1 44 53 pm](https://cloud.githubusercontent.com/assets/3418772/19412157/a01ba9b0-92dd-11e6-9606-6eaba278365d.png)

**Comment by zwhitchcox** [comment]
I know haha...I removed it a while ago...been meaning to put it back online

**Comment by DennisLfromGA** [comment]
No problemmo, just thought you might not be aware of it. ;)

**Comment by zwhitchcox** [comment]
I appreciate it!!

Thanks, we're back in business again ;) zanehitchcox.com

**Comment by DennisLfromGA** [comment]
U of T - *Cool beans!*

**Comment by zwhitchcox** [comment]
Lol, University of Tennessee?? That's my alma mater

**Comment by DennisLfromGA** [comment]
Yeah, sorry. Nice resume btw

**Comment by zwhitchcox** [comment]
Haha thanks! Did you make one??

**Comment by DennisLfromGA** [comment]
Nope, and glad I don't need one anymore. ,-)
I've been retired for a number of years; I just play around with crouton and Chromebook Central now mostly.

**Comment by zwhitchcox** [comment]
Ohhh ok, haha...I envy you there!
